MODEL:
  TYPE: generalized_rcnn
  CONV_BODY: FPN.add_fpn_ResNet152_conv5_body
  NUM_CLASSES: 2
  FASTER_RCNN: True
  MASK_ON: True
NUM_GPUS: 8
LOG_IMAGES: False
DATA_LOADER:
  NUM_THREADS: 8
  PROCESS_POOL_LOADER: True
GRAY_IMAGES: True
PIXEL_MEANS: [[[0, 0, 0]]]
DEDUP_BOXES: 0.250  # 1 / 8. default 1 / 16.
SOLVER:
  WEIGHT_DECAY: 0.0001
  LR_POLICY: steps_with_decay
  # 2x schedule (note TRAIN.IMS_PER_BATCH: 1)
  BASE_LR: 0.01
  GAMMA: 0.1
  MAX_ITER: 360000
  STEPS: [0, 100000, 150000, 200000]
  WARM_UP_FACTOR: 0.01
  WARM_UP_ITERS: 10000
FPN:
  FPN_ON: True
  MULTILEVEL_ROIS: True
  MULTILEVEL_RPN: True
  RPN_ANCHOR_START_SIZE: 8 # default 32
  RPN_ASPECT_RATIOS: (0.2, 0.5, 1, 2, 5)
RPN:
  # RPN Anchor sizes not used by FPN.RPN
  SIZES: (8, 16, 32, 64, 128) # default (64, 128, 256, 512)
  STRIDE: 8 # default 16
  ASPECT_RATIOS: (0.2, 0.5, 1, 2, 5)
RESNETS:
  STRIDE_1X1: False  # default True for MSRA; False for C2 or Torch models
  TRANS_FUNC: bottleneck_transformation
  NUM_GROUPS: 32
  WIDTH_PER_GROUP: 8
FAST_RCNN:
  ROI_BOX_HEAD: fast_rcnn_heads.add_roi_2mlp_head
  ROI_XFORM_METHOD: RoIAlign
  ROI_XFORM_RESOLUTION: 14 # previously 7 but default 14
  ROI_XFORM_SAMPLING_RATIO: 2
MRCNN:
  ROI_MASK_HEAD: mask_rcnn_heads.mask_rcnn_fcn_head_v1up4convs
  RESOLUTION: 28  # (output mask resolution) default 14
  ROI_XFORM_METHOD: RoIAlign
  ROI_XFORM_RESOLUTION: 14  # default 7
  ROI_XFORM_SAMPLING_RATIO: 2  # default 0
  DILATION: 1  # default 2
  CONV_INIT: MSRAFill  # default GaussianFill
  WEIGHT_LOSS_MASK: 1.2 # default 1.0
TRAIN:
  WEIGHTS: https://s3-us-west-2.amazonaws.com/detectron/ImageNetPretrained/25093814/X-152-32x8d-IN5k.pkl
  DATASETS: ('nuclei_stage_1_local_train_split',)
  SCALES: (800, 900, 1000, 1100, 1200)  # Scale jitter
  MAX_SIZE: 1333
  IMS_PER_BATCH: 1
  BATCH_SIZE_PER_IM: 512
  RPN_PRE_NMS_TOP_N: 2000  # Per FPN level
  SNAPSHOT_ITERS: 8000
  NORMALIZE_CLASSES: True
  USE_INVERSE: False
  USE_FLIPPED: False
  USE_AUGMENTOR: True
  USE_MASK_AUGMENTOR: False
  RPN_STRADDLE_THRESH: -1  # default 0
  USE_BBOX_AUGMENTOR: False
TEST:
  DATASETS: ('nuclei_stage_1_local_val_split', )
  COMPETITION_MODE: False
  SCALES: (800,)
  MAX_SIZE: 1333
  NMS: 0.7
  SOFT_NMS:
    ENABLED: True
    METHOD: gaussian
    SIGMA: 0.5
  BBOX_VOTE:
    ENABLED: True
    VOTE_TH: 0.9
  RPN_PRE_NMS_TOP_N: 1000  # Per FPN level
  RPN_POST_NMS_TOP_N: 1000
  DETECTIONS_PER_IM: 500
  RPN_MIN_SIZE: 5
  BBOX_AUG:
    ENABLED: True
    SCORE_HEUR: UNION
    COORD_HEUR: UNION
    H_FLIP: True
    INVERT: True
    SCALES: (400, 500, 600, 700, 900, 1000, 1100, 1200)
    MAX_SIZE: 2000
    SCALE_H_FLIP: True
    SCALE_SIZE_DEP: False
    ASPECT_RATIOS: ()
    ASPECT_RATIO_H_FLIP: False
  MASK_AUG:
    ENABLED: True
    HEUR: SOFT_AVG  # default SOFT_AVG
    H_FLIP: True
    INVERT: True
    SCALES: (900, 1000, 1100, 1200)
    MAX_SIZE: 2000
    SCALE_H_FLIP: True
    SCALE_SIZE_DEP: False
    ASPECT_RATIOS: ()
    ASPECT_RATIO_H_FLIP: False
VIS_TH: 0.7
OUTPUT_DIR: .